name: My super CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  workflow_dispatch:

jobs:
  my-first-job:
    runs-on: ubuntu-latest

    steps:
      - name: Hello World!
        run: |
          mkdir tmp
          echo Hello world! >> tmp/file.txt

      - name: Save file
        uses: actions/upload-artifact@v3
        with:
          name: report
          path: tmp/file.txt





