name: My super CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  workflow_dispatch:

jobs:
  my-first-job:
    runs-on: ubuntu-latest

    steps:
      - name: Hello World!
        run: echo Hello world!
